language: go
dist: bionic

go:
  - 1.13.x

node_js:
  - 10.16.x

before_install:
  - cd app

install:
  - npm install --prefix views
  - go get -d ./...

jobs:
  include:
    - name: Gofmt check
      stage: build
      script: "[[ -z `go fmt ./...` ]]"
    - name: Go & Node.js build
      stage: build
      script:
        - npm build --prefix views
        - go build ./...

branches:
  except:
    - /^exp-.*$/
