language: go
dist: bionic

go:
  - 1.13.x

before_install:
  - cd app

install:
  - go get -d ./...

jobs:
  include:
    - name: Gofmt check
      stage: build
      script: "[[ -z `go fmt ./...` ]]"
    - name: Go build
      stage: build
      script: "go build ./..."

branches:
  except:
    - /^exp-.*$/
